# Generated by Django 4.0 on 2021-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='numComments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
