# Generated by Django 4.0 on 2022-01-02 01:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manga', '0003_manga_favorites_manga_star_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='numComments',
            new_name='numReviews',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='star',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='review',
            name='manga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.manga'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
