# Generated by Django 4.0 on 2021-12-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0003_alter_chapterimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='url',
            new_name='name',
        ),
    ]
